org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

loom_version=1.15.5
java_version=17
compat_layer=legacy
input_layer=legacy

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
fabric_version=0.92.6+1.20.1

mod_version=1.0.14
maven_group=kr.planetearth
archives_base_name=planetmap-mc1.20.1
